CREATE TABLE week_day_use(
    week_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    week_day TEXT NOT NULL,
    morning BOOLEAN NOT NULL DEFAULT true,
    completed BOOLEAN NOT NULL DEFAULT false,
    week_product INTEGER REFERENCES product(product_id) ON DELETE CASCADE NOT NULL
);


